# TensorFlow Basics

In [1]:
import tensorflow as tf 

In [2]:
tf.constant('Hellos Word')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hellos Word'>

In [3]:
hello = tf.constant('Hellos Word')
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [4]:
x = tf.constant(100)
type(x)

tensorflow.python.framework.ops.EagerTensor

vamos a crear nuestra sesscion de tensor flow para poder realizar operaciones con los objetos creados

En versione anteriores esto era necesario, en la que tenemos instalada que es la version 2.xx podemos utilizar los tensores de manera directa

si queremos hacer que tensor se comporte como antes pues:

**import tensorflow.compat.v1 as tf**

*tf.disable_v2_behavior()*

*sess = tf.Session()*



In [5]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [6]:
print(hello)

tf.Tensor(b'Hellos Word', shape=(), dtype=string)


In [7]:
# Operaciones

In [11]:
x = tf.constant(2)

In [12]:
y = tf.constant(3)

In [16]:
print(f'Suma: {x+y}')

Suma: 5


esto se utilizaba antes para guardar un lugar resevado con un tipo de dato para un tensor que aun no lo haciamos pero queriamo tenber la varaible en la que se tendria que alojar, pero en la nueva version de tensor flow no es necesario por que se le da a la varaible el tensor directamente

In [17]:
x = tf.placeholder() 

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [18]:
def doble(x):
    return x * 2

x_data = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
result = doble(x_data)
print(result)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


tensor tiene sus manera de lidiar con suma resta y etc, de la manera que lo hicimos arriba pero tambien con fucciones que lo hacen elemento a elemento simepre y cuando las matrices sean compatibles

In [19]:
add = tf.add(x,y)
add

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [20]:
# --- Definir tensores ---
x = tf.constant([10, 20, 30], dtype=tf.float32)
y = tf.constant([1, 2, 3], dtype=tf.float32)

# --- Operaciones ---
add = x + y            # Suma
sub = x - y            # Resta
mul = x * y            # Multiplicación
div = x / y            # División

# --- Imprimir resultados ---
print("Operations with Constants")
print("Addition:", add.numpy())
print("Subtraction:", sub.numpy())
print("Multiplication:", mul.numpy())
print("Division:", div.numpy())

Operations with Constants
Addition: [11. 22. 33.]
Subtraction: [ 9. 18. 27.]
Multiplication: [10. 40. 90.]
Division: [10. 10. 10.]


In [21]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [22]:
mat1 =tf.constant(a)
mat2 = tf.constant(b)

In [23]:
matrix_multi = tf.matmul(mat1,mat2)

In [24]:
matrix_multi

<tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[20.]])>